export const creators = [
  {
    id: "1",
    name: "Priya Sharma",
    handle: "@priyacreates",
    avatar: "PS",
    trustScore: 82,
    niche: "Lifestyle & Wellness",
    platform: "instagram",
    followers: 245000,
    location: "Mumbai",
    country: "India",
    fitScore: 88,
    engagementRate: 4.8,
    estimatedCost: 1800,
    audienceAge: "25-34",
    audienceWomen: 72,
    responseTime: "8h",
    bio: "Lifestyle storyteller focused on wellness, routines, and clean beauty.",
    pastCampaigns: [
      { name: "GlowNaturals Serum Launch", result: "4.2% CTR", budget: "$2,400", month: "Oct 2025" },
      { name: "YogaFlow App Sprint", result: "1,240 installs", budget: "$1,900", month: "Dec 2025" },
      { name: "EcoBottle Awareness", result: "8.1% engagement", budget: "$1,300", month: "Jan 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 420, engagement: 4.2 },
      { month: "Nov", impressions: 470, engagement: 4.5 },
      { month: "Dec", impressions: 520, engagement: 4.7 },
      { month: "Jan", impressions: 560, engagement: 4.9 },
      { month: "Feb", impressions: 585, engagement: 5.0 },
    ],
  },
  {
    id: "2",
    name: "Arjun Menon",
    handle: "@arjunmenon",
    avatar: "AM",
    trustScore: 76,
    niche: "Tech & Gadgets",
    platform: "youtube",
    followers: 512000,
    location: "Bangalore",
    country: "India",
    fitScore: 72,
    engagementRate: 3.6,
    estimatedCost: 3200,
    audienceAge: "18-34",
    audienceWomen: 35,
    responseTime: "12h",
    bio: "Consumer tech reviewer covering smartphones, wearables, and software tips.",
    pastCampaigns: [
      { name: "NovaPhone X Review", result: "2.8M views", budget: "$4,800", month: "Nov 2025" },
      { name: "WirePro Earbuds", result: "3.6% CTR", budget: "$3,500", month: "Jan 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 980, engagement: 3.1 },
      { month: "Nov", impressions: 1120, engagement: 3.3 },
      { month: "Dec", impressions: 1040, engagement: 3.4 },
      { month: "Jan", impressions: 1080, engagement: 3.5 },
      { month: "Feb", impressions: 1150, engagement: 3.6 },
    ],
  },
  {
    id: "3",
    name: "Sneha Reddy",
    handle: "@snehafit",
    avatar: "SR",
    trustScore: 91,
    niche: "Fitness & Health",
    platform: "instagram",
    followers: 189000,
    location: "Hyderabad",
    country: "India",
    fitScore: 94,
    engagementRate: 5.5,
    estimatedCost: 2100,
    audienceAge: "18-30",
    audienceWomen: 64,
    responseTime: "6h",
    bio: "Fitness coach sharing practical workouts and nutrition plans for busy professionals.",
    pastCampaigns: [
      { name: "FitNation Challenge", result: "10.2% engagement", budget: "$2,000", month: "Dec 2025" },
      { name: "PulseBand Launch", result: "2,920 leads", budget: "$2,700", month: "Feb 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 360, engagement: 5.0 },
      { month: "Nov", impressions: 390, engagement: 5.2 },
      { month: "Dec", impressions: 420, engagement: 5.3 },
      { month: "Jan", impressions: 450, engagement: 5.4 },
      { month: "Feb", impressions: 470, engagement: 5.5 },
    ],
  },
  {
    id: "4",
    name: "Vikram Das",
    handle: "@vikramtravels",
    avatar: "VD",
    trustScore: 68,
    niche: "Travel & Adventure",
    platform: "youtube",
    followers: 320000,
    location: "Delhi",
    country: "India",
    fitScore: 65,
    engagementRate: 2.9,
    estimatedCost: 2700,
    audienceAge: "18-35",
    audienceWomen: 41,
    responseTime: "24h",
    bio: "Adventure vlogger focused on budget travel and destination storytelling.",
    pastCampaigns: [
      { name: "WanderLux Escapes", result: "1.4M views", budget: "$3,000", month: "Sep 2025" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 610, engagement: 2.5 },
      { month: "Nov", impressions: 640, engagement: 2.6 },
      { month: "Dec", impressions: 650, engagement: 2.7 },
      { month: "Jan", impressions: 670, engagement: 2.8 },
      { month: "Feb", impressions: 690, engagement: 2.9 },
    ],
  },
  {
    id: "5",
    name: "Ananya Patel",
    handle: "@ananyacooks",
    avatar: "AP",
    trustScore: 85,
    niche: "Food & Recipes",
    platform: "instagram",
    followers: 156000,
    location: "Ahmedabad",
    country: "India",
    fitScore: 79,
    engagementRate: 4.1,
    estimatedCost: 1500,
    audienceAge: "25-44",
    audienceWomen: 69,
    responseTime: "10h",
    bio: "Home chef creating fast, healthy Indian recipes and kitchen hacks.",
    pastCampaigns: [
      { name: "NatureBites Snacks", result: "6.1% CTR", budget: "$1,450", month: "Jan 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 270, engagement: 3.6 },
      { month: "Nov", impressions: 290, engagement: 3.8 },
      { month: "Dec", impressions: 310, engagement: 3.9 },
      { month: "Jan", impressions: 330, engagement: 4.0 },
      { month: "Feb", impressions: 360, engagement: 4.1 },
    ],
  },
  {
    id: "6",
    name: "Rohan Kapoor",
    handle: "@rohangaming",
    avatar: "RK",
    trustScore: 73,
    niche: "Gaming & Esports",
    platform: "youtube",
    followers: 890000,
    location: "Pune",
    country: "India",
    fitScore: 68,
    engagementRate: 3.2,
    estimatedCost: 4800,
    audienceAge: "16-28",
    audienceWomen: 22,
    responseTime: "18h",
    bio: "Esports commentator and game reviewer with a strong live-stream audience.",
    pastCampaigns: [
      { name: "GameHub Controller Pro", result: "1,900 purchases", budget: "$5,200", month: "Feb 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 1300, engagement: 2.8 },
      { month: "Nov", impressions: 1360, engagement: 2.9 },
      { month: "Dec", impressions: 1400, engagement: 3.0 },
      { month: "Jan", impressions: 1440, engagement: 3.1 },
      { month: "Feb", impressions: 1510, engagement: 3.2 },
    ],
  },
  {
    id: "7",
    name: "Meera Iyer",
    handle: "@meerastyle",
    avatar: "MI",
    trustScore: 88,
    niche: "Fashion & Beauty",
    platform: "instagram",
    followers: 278000,
    location: "Chennai",
    country: "India",
    fitScore: 91,
    engagementRate: 5.1,
    estimatedCost: 2600,
    audienceAge: "18-34",
    audienceWomen: 81,
    responseTime: "7h",
    bio: "Fashion creator focused on practical style edits and affordable beauty.",
    pastCampaigns: [
      { name: "StyleVerse Festive Edit", result: "9.5% engagement", budget: "$2,300", month: "Nov 2025" },
      { name: "Verdant Beauty UGC", result: "4.3% CTR", budget: "$2,800", month: "Feb 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 430, engagement: 4.6 },
      { month: "Nov", impressions: 470, engagement: 4.8 },
      { month: "Dec", impressions: 490, engagement: 4.9 },
      { month: "Jan", impressions: 520, engagement: 5.0 },
      { month: "Feb", impressions: 545, engagement: 5.1 },
    ],
  },
  {
    id: "8",
    name: "Karthik Nair",
    handle: "@karthikedu",
    avatar: "KN",
    trustScore: 79,
    niche: "Education & Career",
    platform: "youtube",
    followers: 420000,
    location: "Kochi",
    country: "India",
    fitScore: 76,
    engagementRate: 3.8,
    estimatedCost: 2400,
    audienceAge: "18-30",
    audienceWomen: 46,
    responseTime: "14h",
    bio: "Career educator breaking down interview prep, resume strategy, and upskilling.",
    pastCampaigns: [
      { name: "EduSpark Upskilling Week", result: "3,100 signups", budget: "$2,900", month: "Jan 2026" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 700, engagement: 3.2 },
      { month: "Nov", impressions: 740, engagement: 3.4 },
      { month: "Dec", impressions: 770, engagement: 3.5 },
      { month: "Jan", impressions: 810, engagement: 3.7 },
      { month: "Feb", impressions: 850, engagement: 3.8 },
    ],
  },
  {
    id: "9",
    name: "Diya Bose",
    handle: "@diyaarts",
    avatar: "DB",
    trustScore: 86,
    niche: "Art & DIY Crafts",
    platform: "instagram",
    followers: 134000,
    location: "Kolkata",
    country: "India",
    fitScore: 83,
    engagementRate: 4.6,
    estimatedCost: 1300,
    audienceAge: "18-35",
    audienceWomen: 67,
    responseTime: "9h",
    bio: "DIY creator specializing in craft tutorials and handmade design projects.",
    pastCampaigns: [
      { name: "HomeNest Decor Challenge", result: "7.4% engagement", budget: "$1,350", month: "Dec 2025" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 230, engagement: 4.1 },
      { month: "Nov", impressions: 245, engagement: 4.2 },
      { month: "Dec", impressions: 260, engagement: 4.3 },
      { month: "Jan", impressions: 275, engagement: 4.4 },
      { month: "Feb", impressions: 295, engagement: 4.6 },
    ],
  },
  {
    id: "10",
    name: "Aditya Singh",
    handle: "@adityavlogs",
    avatar: "AS",
    trustScore: 71,
    niche: "Vlogging & Lifestyle",
    platform: "youtube",
    followers: 650000,
    location: "Jaipur",
    country: "India",
    fitScore: 74,
    engagementRate: 3.1,
    estimatedCost: 3600,
    audienceAge: "18-34",
    audienceWomen: 38,
    responseTime: "20h",
    bio: "Daily vlogger sharing productivity, travel, and creator life content.",
    pastCampaigns: [
      { name: "FinWise Budget Planner", result: "2.9% CTR", budget: "$4,100", month: "Nov 2025" },
    ],
    monthlyPerformance: [
      { month: "Oct", impressions: 940, engagement: 2.7 },
      { month: "Nov", impressions: 990, engagement: 2.8 },
      { month: "Dec", impressions: 1020, engagement: 2.9 },
      { month: "Jan", impressions: 1060, engagement: 3.0 },
      { month: "Feb", impressions: 1090, engagement: 3.1 },
    ],
  },
];

export function formatFollowers(count) {
  if (count >= 1000000) {
    return `${(count / 1000000).toFixed(1)}M`;
  }
  return `${Math.round(count / 1000)}K`;
}

